"""dossie e expurgo

Revision ID: 966ce889d9f0
Revises: 66a5f1cd51a0
Create Date: 2026-07-13 23:29:15.884581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '966ce889d9f0'
down_revision: Union[str, None] = '66a5f1cd51a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidato', sa.Column('dossie_pdf_key', sa.String(length=300), nullable=True))
    op.add_column('candidato', sa.Column('dossie_gerado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidato', sa.Column('arquivos_expurgados_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidato', 'arquivos_expurgados_em')
    op.drop_column('candidato', 'dossie_gerado_em')
    op.drop_column('candidato', 'dossie_pdf_key')
    # ### end Alembic commands ###
